"""add_session_fields_to_meetings

Revision ID: 176a48a6b858
Revises: b2c3d4e5f6a7
Create Date: 2026-07-09 03:49:08.068756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '176a48a6b858'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('job_role', sa.String(length=255), nullable=True))
    op.add_column('meetings', sa.Column('meeting_link', sa.String(length=500), nullable=True))
    op.add_column('meetings', sa.Column('expected_duration_minutes', sa.Integer(), nullable=True))
    op.add_column('meetings', sa.Column('session_start', sa.DateTime(), nullable=True))
    op.add_column('meetings', sa.Column('session_end', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'session_end')
    op.drop_column('meetings', 'session_start')
    op.drop_column('meetings', 'expected_duration_minutes')
    op.drop_column('meetings', 'meeting_link')
    op.drop_column('meetings', 'job_role')
    # ### end Alembic commands ###
